#!/usr/bin/env python3
"""Render actual chronological checkpoints into a labeled, fully decoded MP4."""
import argparse,copy,hashlib,json,subprocess
from pathlib import Path
from playwright.sync_api import sync_playwright

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--output',type=Path,required=True);a=ap.parse_args();out=a.output;state_raw=(out/'data.json').read_bytes();state=json.loads(state_raw);assert not state['fixture'];frames=out/'replay-frames';frames.mkdir(exist_ok=True)
 sequence=sorted([(x['timestamp'],p['id'],x['index']) for p in state['policies'] for x in p['points'] if x['completed']],key=lambda x:(x[0],x[1]));assert sequence
 events=[json.loads(x) for x in (out/'events.jsonl').read_text().splitlines() if x];recorded=[]
 with sync_playwright() as pw:
  browser=pw.chromium.launch(executable_path='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless=True);page=browser.new_page(viewport={'width':1920,'height':1080});errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.goto((out/'index.html').as_uri());page.uncheck('#live')
  page.add_style_tag(content='main{padding:18px;max-width:1920px}h1{font-size:26px}main>p,main>.row,main>.banner:last-child,main>section,#best-board,#heartbeat,.hash,.pair a,#board-panel>details,.banner>.small,#validity{display:none}.columns{display:grid;grid-template-columns:0.7fr 1.3fr;gap:12px}.columns>.panel:first-child{position:static}.chart{height:300px}.columns p.small,.columns #legend{display:none}.panel{margin-top:8px;padding:12px}.policies{margin:8px 0}.policy{padding:8px}.cost{font-size:20px}.pair h3{font-size:16px;margin:4px}.board{height:285px;aspect-ratio:auto;object-fit:contain}.banner{margin:6px 0;padding:8px}.pair{gap:6px}#decision-card{font-size:14px}#decision-card p{margin:5px 0}.policies .small{display:none}#decision-card p.small{display:block}')
  page.evaluate("""(d)=>{const card=document.createElement('div');card.id='video-intro';card.style='position:fixed;inset:0;background:#091320;color:#e8f0f8;padding:90px;font:28px/1.6 system-ui;z-index:99';const h=document.createElement('h1');h.textContent='Copper Scar · test the optimizer, not just the board';h.style='font-size:50px';card.append(h);for(const text of ['HIGHER LOOP · Agent-authored policy hypotheses → frozen matched campaign → measured cost at 3 decisions → keep or reject policy.','LOWER LOOP · Propose placement / via edit → full-board six-layer route → native evaluation → retain or reject.',...d.policies.map(p=>p.id+': '+p.hypothesis),'Same four-candidate library, parent board, native constraints and routing budget. Only ranking differs.','This is a prior-informed single-board pilot. Lower steps use deterministic ranking, not per-step LLM inference.']){const p=document.createElement('p');p.textContent=text;card.append(p)}document.body.append(card)}""",state)
  target=frames/'000.png';page.screenshot(path=str(target));recorded.append({'frame':target.name,'status':'authored hypotheses and frozen protocol'});page.locator('#video-intro').evaluate('(e)=>e.remove()')
  for number,(at,pid,index) in enumerate(sequence,1):
   frame=copy.deepcopy(state);frame['latest_event_at']=at;frame['event_count']=sum(e['timestamp_utc']<=at for e in events);frame['decisions']=[];frame['decision_artifacts']=[];frame['remote_receipts']=None
   for p in frame['policies']:
    p['points']=[x for x in p['points'] if x['timestamp']<=at];p['active_index']=None;p['state']='recorded checkpoint';p['completed_decisions']=sum(x['index']!=0 for x in p['points']);p['routed_completed']=sum(x['routed_completed'] for x in p['points']);p['routed_dispatch_count']=max([x['raw_lower'].get('routed_dispatch_count',0) for x in p['points']] or [0]);p['route_wall_seconds']=sum(x.get('route_elapsed_seconds') or 0 for x in p['points']);p['decision_wall_seconds']=sum(x['elapsed_seconds'] or 0 for x in p['points']);p['cost_at_n']=p['points'][-1]['best'] if p['completed_decisions']==frame['attempt_budget'] else None
   page.evaluate('(d)=>window.EXPERIMENT=d',frame);page.evaluate('([p,i])=>selectCheckpoint(p,i)',[pid,index]);page.locator('h1').evaluate('(e)=>e.textContent="ACTUAL CHECKPOINT REPLAY · policy ranking pilot"');page.wait_for_function('Array.from(document.images).every(i=>i.complete)');target=frames/f'{number:03}.png';page.screenshot(path=str(target));recorded.append({'frame':target.name,'timestamp':at,'policy':pid,'decision':index})
  page.evaluate('(d)=>window.EXPERIMENT=d',state);pid=state['policies'][-1]['id'];index=max(x['index'] for x in state['policies'][-1]['points']);page.evaluate('([p,i])=>selectCheckpoint(p,i)',[pid,index]);page.locator('h1').evaluate('(e,t)=>e.textContent=t','COMPARISON RECORDED · kept '+str(state['decisions'][-1]['decision']['kept_policy']) if state['decisions'] else 'IN PROGRESS · cost at 3 decisions remains unavailable');page.evaluate('''(d)=>{const panel=document.createElement('div');panel.className='banner';const lines=d.decisions.length?['HIGHER-LEVEL DECISION: '+d.decisions.at(-1).decision.kept_policy,d.common_protocol.decision_rule]:['COMPARISON IN PROGRESS','No final policy selection is inferred.'];for(const a of d.decision_artifacts||[])if(a.kind.startsWith('next-campaign/'))lines.push('Separate next-campaign evidence: '+a.kind);for(const text of lines){const p=document.createElement('p');p.textContent=text;panel.append(p)}document.querySelector('.columns>.panel').append(panel)}''',state);page.wait_for_function('Array.from(document.images).every(i=>i.complete)');target=frames/f'{len(recorded):03}.png';page.screenshot(path=str(target));recorded.append({'frame':target.name,'status':'current complete comparison' if state['decisions'] else 'incomplete checkpoint'})
  assert not errors,errors;browser.close()
 # Explicit current frame list avoids including leftovers from earlier longer exports.
 listing=frames/'frames.txt';listing.write_text(''.join("file '"+r['frame']+"'\nduration "+str(8 if i in (0,len(recorded)-1) else 4)+"\n" for i,r in enumerate(recorded))+"file '"+recorded[-1]['frame']+"'\n")
 video=out/'two-level-replay.mp4';subprocess.run(['ffmpeg','-y','-loglevel','error','-f','concat','-safe','0','-i',str(listing),'-vf','fps=24,format=yuv420p','-c:v','libx264','-crf','20','-movflags','+faststart',str(video)],check=True);subprocess.run(['ffmpeg','-v','error','-i',str(video),'-f','null','-'],check=True)
 receipt={'fixture':False,'comparison_complete':bool(state['decisions']),'source_events_sha256':state['events_sha256'],'source_state_sha256':hashlib.sha256(state_raw).hexdigest(),'frames':recorded,'video_sha256':hashlib.sha256(video.read_bytes()).hexdigest(),'video_bytes':video.stat().st_size,'full_decode_pass':True};(out/'replay-verified.json').write_text(json.dumps(receipt,indent=2));print(json.dumps(receipt))
if __name__=='__main__':main()
