"""Public evidence summaries; these are not model inference or chain-of-thought."""
def summarize(policy,point):
 a=point.get('action') or {};idx=point['index'];c=point.get('attempted') or {};best=point.get('best') or {};edits=point.get('actual_edits') or {}
 proposal=('Move '+', '.join(a.get('refs',[]))+' by '+str(a.get('translation_mm'))+' mm, rotation '+str(a.get('rotation_deg',0))+' degrees.') if a.get('kind')=='group_pose' else ('Add '+str(len(a.get('via_sites',[])))+' explicit CAN2_H via sites, preserving existing copper.') if a.get('kind')=='local_topology_replan' else 'No feasible new proposal selected.'
 screens=[s for s in policy.get('screened',[]) if s['index']==idx]
 alternatives=[{'candidate':s.get('action',{}).get('id'),'feasible':s.get('feasible'),'split_groups':s.get('split_group_count'),'physical_errors':s.get('nativecost',{}).get('physical_errors')} for s in screens]
 split='; '.join(', '.join(p.get('pad',p.get('uuid','?')) for p in g) for g in point.get('split_pad_groups',[]))
 decision='Retained in this independent policy arm.' if point.get('retained') else 'Rejected; retained incumbent remains at '+str(best.get('opens'))+' missing pairs.'
 if split:decision+=' Original connected pad group split: '+split+'.'
 return {'label':'Recorded evidence and decision summary, not an LLM inference trace','policy':policy['id'],'decision_index':idx,'hypothesis':a.get('hypothesis',policy.get('hypothesis')),'proposal':proposal,'alternatives':alternatives,'test':('Whole-board routing across all six copper layers followed by native pad-group, physical, manufacturing and invariant checks; router wall time '+str(point.get('route_elapsed_seconds'))+' seconds.') if point.get('routed_completed') else 'Screening only; no full routing result.','evidence':str(c.get('opens'))+' missing pairs, '+str(c.get('physical_errors'))+' physical errors, '+str(c.get('warnings'))+' warnings.','decision':decision,'causal_limit':('Both first attempts closed the identical CAN2_H join through existing vias on In4.Cu. Challenger avoided the R123 collateral split; its new x141 vias remained dangling. No no-update control isolates the normalizer contribution.') if idx==1 else 'Prior-informed single-board finite-library ranking pilot; no statistical or general convergence claim.','qualification':'Board remains unqualified while missing connections or acceptance failures remain.','raw_receipt':point.get('receipt_href'),'raw_receipt_sha256':point.get('receipt_sha256')}
