import argparse,hashlib,json
from pathlib import Path
import pcbnew as p
ap=argparse.ArgumentParser();ap.add_argument('parent',type=Path);ap.add_argument('output',type=Path);a=ap.parse_args();path=a.parent/'pcbgolf.kicad_pcb';source_hash=hashlib.sha256(path.read_bytes()).hexdigest();project=a.parent/'pcbgolf.kicad_pro';project_hash=hashlib.sha256(project.read_bytes()).hexdigest();manager=p.SETTINGS_MANAGER();manager.LoadProject(str(project));b=p.LoadBoard(str(path));b.SetProject(manager.GetProject(str(project)));assert p.ZONE_FILLER(b).Fill(b.Zones());connection=b.GetConnectivity();connection.Build(b);connection.RecalculateRatsnest();fs={f.GetReference():f for f in b.GetFootprints()};f=fs['R79'];anchor=next(q for q in f.Pads() if q.GetNumber()=='1');assert [p.ToMM(anchor.GetPosition().x),p.ToMM(anchor.GetPosition().y)]==[155.05,95.75];assert [p.ToMM(f.GetPosition().x),p.ToMM(f.GetPosition().y)]==[155.5,95.75] and f.GetOrientationDegrees()==0
free=next(q for q in f.Pads() if q.GetNumber()=='2')
def group(pad):
 return {q.m_Uuid.AsString():q.GetParentFootprint().GetReference()+'.'+q.GetNumber() for q in list(connection.GetConnectedItems(pad))+[pad] if isinstance(q,p.PAD)}
anchor_group=group(anchor);free_group=group(free)
assert set(free_group)=={free.m_Uuid.AsString()},'Free pad is already connected; do not repeat the pivot'
assert set(anchor_group.values())=={'R79.1','Q3.1','U3.117','R85.2'},'Connected anchor group changed'
nets=sorted({q.GetNetname() for q in f.Pads() if q.GetNetname()});d=dict(schema_version=1,kind='group_pose',id='r79-preserve-connected-contact',refs=['R79'],locked_refs=sorted(set(fs)-{'R79'}),parent_board_sha256=hashlib.sha256(path.read_bytes()).hexdigest(),from_poses={'R79':dict(x_mm=155.5,y_mm=95.75,angle_deg=0)},translation_mm=[-.45,.45],rotation_deg=-90,group='port_channel_1',group_members=['R79'],nets=nets,net='GND',copper_policy='preserve_all',preserve_foreign_copper=True,boundary_via_policy='preserve_existing_sites',preserved_pad_uuid=anchor.m_Uuid.AsString(),preserved_pad_position_mm=[155.05,95.75],proxy_before={'total':None},proxy_after={'total':None},reason='Measured R123 moves cut connected pad groups; preserve the R79 gate anchor and all existing copper while moving its isolated GND pad',hypothesis='A symmetry-preserving passive pivot can improve pad access without creating restoration debt',feedback_used=['stage1-20260913-090014-e1ebe9','/Users/philippe/Documents/Codex/2026-09-12/realtime-voice-chat/outputs/next-placement-policy-research/proposals.json']);d['native_contact_binding']=dict(source_board_sha256=source_hash,source_project_sha256=project_hash,anchor_group=anchor_group,free_group=free_group,CAD_saved=False);assert hashlib.sha256(path.read_bytes()).hexdigest()==source_hash and hashlib.sha256(project.read_bytes()).hexdigest()==project_hash;a.output.write_text(json.dumps(d,indent=2))
